### ISSUE TITLE
Pre-Publishing Tests Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cloud-azure#15]
Pre-Publishing Tests

- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, draft-guides
- [x] Read through the guide 
- [ ] Clone repo and test finish directory with no error
   - ran `mvn package` and `docker build ...`, and have no problem
   - will be done by post-publish test
- [x] Run `diff -r start/ finish/` 
- [ ] Follow the instruction in the guide to test that it is working
   - will be done by post-publish test
- Use the `copy` buttons instead of typing 
- [x] Check that the release date on the readme.adoc is the publishing date
